### ISSUE TITLE
Support Region ignore

### ISSUE THREAD

**Issue by kernelbin** [twilightgod/AndroidBrokenScreenSaver#1]
I broken my phone screen too, it have a similar symptom, but it click on a point instead of a line.
So I suggest to add functions to block a region (can be a line or a point)

by the way, how to build it?

**Comment by twilightgod** [comment]
Sorry, I don't have Android phone anymore, I can't add more feature and test it.
It's built with Android Studio.
Feel free to fork it and make the change.

**Comment by kernelbin** [comment]
Ok, thank you very much!
